# conda-build recipe for Caelus Python Library

package:
  name: caelus
  version: "v4.0.0"

source:
  git_rev: main
  git_url: "../../../"

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - pip
    - six
    - numpy
    - matplotlib
    - pyyaml
    - ply
    - pytz
    - jinja2
    - vtk
    - pyvista

about:
  home: https://github.com/sayerhs/cpl
  license: "Apache License 2.0"
  summmary: Python library for use with Caelus CML and OpenFOAM
